server:
  host: localhost

spring:
  mvc:
    log-resolved-exception: true

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false

  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  datasource:
    url: jdbc:h2:~/db-dev
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: always
    data: classpath*:data/init.sql
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jmx:
    enabled: false

  application:
    admin:
      enabled: false
